// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iltppjgwfmftbpdpfypx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsdHBwamd3Zm1mdGJwZHBmeXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NDYwNDYsImV4cCI6MjA2MzAyMjA0Nn0.yW_zT7tCEBeXG8vVKmjQ09EyqC_Rxbj9P0GJbRIWZQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);